name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Breaking Changes'
    labels:
        - 'breaking change'
  - title: 'Enhancements'
    labels:
      - 'type: enhancement'
  - title: 'Performance'
    labels:
      - 'type: performance'
  - title: 'Bugs Fixed'
    labels:
      - 'type: bug'
  - title: 'Types'
    labels:
      - 'type: types'
  - title: 'Documentation'
    labels:
      - 'type: documentation'
  - title: 'Development'
    labels:
      - 'type: chore'
exclude-labels:
  - 'type: infrastructure'
change-template: '- #$NUMBER $TITLE'
change-title-escapes: '\<*_&`#@'
version-resolver:
  major:
    labels:
      - 'breaking change'
  minor:
    labels:
      - 'type: enhancement'
  patch:
    labels:
      - 'type: bug'
      - 'type: chore'
      - 'type: types'
  default: patch
template: |
  # Essential Links

  * [npm](https://www.npmjs.com/package/ng2-charts)
  * [Docs & Samples](https://valor-software.com/ng2-charts/)

  $CHANGES

  Thanks to $CONTRIBUTORS
